---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: decisive-stump-travel-hack-2024
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  ingressClassName: traefik
  rules:
    - host: admin.0xb1b1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
