---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: decisive-stump-travel-hack-2024
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
