---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: decisive-stump-travel-hack-2024
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      hostAliases:
      - ip: "77.37.209.29"
        hostnames:
        - "minio-travel.0xb1b1.com"
      containers:
      - name: backend
        image: "0xb1b1/ds-backend-travel-hack-2024:latest"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: backend-credentials
        - configMapRef:
            name: backend-config
        env:
        - name: RUST_LOG
          value: "debug"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: decisive-stump-travel-hack-2024
  labels:
    app: worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      hostAliases:
      - ip: "77.37.209.29"
        hostnames:
        - "minio-travel.0xb1b1.com"
      containers:
      - name: worker
        image: "0xb1b1/ds-worker-travel-hack-2024:latest"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: backend-credentials
        - configMapRef:
            name: backend-config
        env:
        - name: RUST_LOG
          value: "debug"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          limits:
            memory: "800Mi"
            cpu: "600m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guests
  namespace: decisive-stump-travel-hack-2024
  labels:
    app: guests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guests
  template:
    metadata:
      labels:
        app: guests
    spec:
      hostAliases:
      - ip: "77.37.209.29"
        hostnames:
        - "minio-travel.0xb1b1.com"
      containers:
      - name: guests
        image: "0xb1b1/ds-guests-travel-hack-2024:latest"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: backend-credentials
        - configMapRef:
            name: backend-config
        env:
        - name: RUST_LOG
          value: "debug"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          limits:
            memory: "800Mi"
            cpu: "600m"
