---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: decisive-stump-travel-hack-2024
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: guests
  namespace: decisive-stump-travel-hack-2024
spec:
  selector:
    app: guests
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
